import { homedir } from "node:os";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { writeFile, mkdir, readFile } from "node:fs/promises";
import type { ProviderAdapter, ProviderInfo, GeneratedFile } from "./types.js";
import type { McpServerDefinition, McpServerConfig } from "../mcp/types.js";
import type { AgentDefinition } from "../agents/types.js";
import { commandExists, runSilent } from "../utils/shell.js";
import { log } from "../utils/logger.js";

const GENERATED_HEADER = "<!-- Generated by agent-stack. Do not edit manually. -->";

export class KiroAdapter implements ProviderAdapter {
  id = "kiro";
  displayName = "Kiro";

  async detect(): Promise<ProviderInfo> {
    const home = homedir();
    const configPaths = [join(home, ".kiro")];
    const installed = await commandExists("kiro");

    let version: string | undefined;
    if (installed) {
      const result = await runSilent("kiro", ["--version"]);
      if (result.exitCode === 0) {
        version = result.stdout.trim();
      }
    }

    // Also check for Kiro as an app on macOS
    const macAppPath = "/Applications/Kiro.app";
    const appExists = existsSync(macAppPath);

    return {
      name: this.id,
      displayName: this.displayName,
      installed: installed || appExists,
      version,
      configPaths: configPaths.filter((p) => existsSync(p)),
    };
  }

  async install(): Promise<void> {
    log.step("Kiro is an IDE — please download it from https://kiro.dev");
    log.info("After installing, run 'agent-stack init' again to configure it.");
  }

  async configureMcp(
    servers: McpServerDefinition[],
    envValues: Record<string, string>
  ): Promise<void> {
    const home = homedir();
    const mcpConfigPath = join(home, ".kiro", "mcp.json");
    const mcpDir = join(home, ".kiro");

    let existing: Record<string, unknown> = {};
    if (existsSync(mcpConfigPath)) {
      try {
        const raw = await readFile(mcpConfigPath, "utf-8");
        existing = JSON.parse(raw);
      } catch {
        existing = {};
      }
    }

    const mcpServers: Record<string, unknown> =
      (existing["mcpServers"] as Record<string, unknown>) ?? {};

    for (const server of servers) {
      const config: Record<string, unknown> = {};
      if (server.command) config["command"] = server.command;
      if (server.args) config["args"] = server.args;

      if (server.env) {
        const env: Record<string, string> = {};
        for (const key of Object.keys(server.env)) {
          env[key] = envValues[key] ?? "";
        }
        config["env"] = env;
      }

      mcpServers[server.name] = config;
      log.success(`MCP server "${server.displayName}" configured for Kiro`);
    }

    existing["mcpServers"] = mcpServers;

    if (!existsSync(mcpDir)) {
      await mkdir(mcpDir, { recursive: true });
    }
    await writeFile(mcpConfigPath, JSON.stringify(existing, null, 2));
  }

  async removeMcp(serverName: string): Promise<void> {
    const mcpConfigPath = join(homedir(), ".kiro", "mcp.json");
    if (!existsSync(mcpConfigPath)) return;

    const raw = await readFile(mcpConfigPath, "utf-8");
    const config = JSON.parse(raw);
    const mcpServers = config["mcpServers"] ?? {};
    delete mcpServers[serverName];
    config["mcpServers"] = mcpServers;
    await writeFile(mcpConfigPath, JSON.stringify(config, null, 2));
  }

  async listMcp(): Promise<McpServerConfig[]> {
    const mcpConfigPath = join(homedir(), ".kiro", "mcp.json");
    if (!existsSync(mcpConfigPath)) return [];

    try {
      const raw = await readFile(mcpConfigPath, "utf-8");
      const config = JSON.parse(raw);
      const mcpServers = (config["mcpServers"] ?? {}) as Record<
        string,
        { command?: string; args?: string[]; env?: Record<string, string> }
      >;

      return Object.entries(mcpServers).map(([name, cfg]) => ({
        name,
        command: cfg.command ?? "",
        args: cfg.args ?? [],
        env: cfg.env,
      }));
    } catch {
      return [];
    }
  }

  async generateAgentConfig(
    agents: AgentDefinition[],
    projectDir: string
  ): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    const relevantAgents = agents.filter(
      (a) => !a.providers || a.providers.includes("kiro")
    );

    if (relevantAgents.length === 0) return files;

    // Generate .kiro/rules/<agent>.md for each agent
    for (const agent of relevantAgents) {
      const sections: string[] = [GENERATED_HEADER, ""];
      sections.push(`# ${agent.name}`);
      sections.push("");

      if (agent.systemPrompt) {
        sections.push(agent.systemPrompt);
        sections.push("");
      }

      if (agent.rules && agent.rules.length > 0) {
        sections.push("## Rules");
        sections.push("");
        for (const rule of agent.rules) {
          sections.push(`- ${rule}`);
        }
        sections.push("");
      }

      const fileName = agent.name.toLowerCase().replace(/\s+/g, "-");
      const filePath = `.kiro/rules/${fileName}.md`;

      files.push({
        path: filePath,
        content: sections.join("\n"),
        action: existsSync(join(projectDir, filePath)) ? "overwrite" : "create",
      });
    }

    return files;
  }
}
