import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { writeFile, mkdir, chmod } from "node:fs/promises";
import { join, dirname, relative, basename } from "node:path";
import { fileURLToPath } from "node:url";
import type { GeneratedFile } from "../providers/types.js";
import type { HarnessParams } from "../detect/harness-params.js";
import { detectHarnessParams } from "../detect/harness-params.js";
import { log } from "../utils/logger.js";

/** Verbatim hooks block — correct Claude Code schema ({matcher, hooks:[{type,command}]}). */
const HOOKS_BLOCK = {
  PreToolUse: [
    {
      matcher: "Bash",
      hooks: [{ type: "command", command: "$CLAUDE_PROJECT_DIR/.claude/hooks/guard-bash.sh" }],
    },
    {
      matcher: "Edit|Write|MultiEdit",
      hooks: [{ type: "command", command: "$CLAUDE_PROJECT_DIR/.claude/hooks/guard-file.sh" }],
    },
  ],
  SessionStart: [
    {
      hooks: [
        { type: "command", command: "$CLAUDE_PROJECT_DIR/.claude/hooks/session-start-context.sh" },
      ],
    },
  ],
  Stop: [
    {
      hooks: [{ type: "command", command: "$CLAUDE_PROJECT_DIR/.claude/hooks/stop-flag-reflect.sh" }],
    },
  ],
  PostToolUse: [
    {
      matcher: "Edit|Write|MultiEdit",
      hooks: [
        { type: "command", command: "$CLAUDE_PROJECT_DIR/.claude/hooks/post-edit-lint.sh" },
        { type: "command", command: "$CLAUDE_PROJECT_DIR/.claude/hooks/post-edit-verify.sh" },
      ],
    },
  ],
};

function templatesRoot(): string {
  const thisDir = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    join(thisDir, "..", "templates", "claude"), // dist/index.js -> ../templates/claude
    join(thisDir, "..", "..", "templates", "claude"), // src/claude/ -> ../../templates/claude
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  throw new Error("Could not find templates/claude");
}

function substitute(text: string, p: HarnessParams): string {
  return text
    .replaceAll("{{PM}}", p.packageManager)
    .replaceAll("{{FORBIDDEN_PM}}", p.forbiddenPms)
    .replaceAll("{{GEN_GLOBS}}", p.generatedGlobs)
    .replaceAll("{{LOCKFILE}}", p.lockfile)
    .replaceAll("{{DOCS_DIR}}", p.docsDir)
    .replaceAll("{{MAIN_BRANCH}}", p.mainBranch);
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function buildSettings(p: HarnessParams): string {
  const allow = [
    ...p.commands.map((c) => `Bash(${c}:*)`),
    "Bash(git status:*)",
    "Bash(git diff:*)",
    "Bash(git log:*)",
    "Bash(git show:*)",
    `Bash(${p.forgeCli} api:*)`,
    `Bash(${p.forgeCli} pr view:*)`,
    `Bash(${p.forgeCli} pr diff:*)`,
    "WebSearch",
  ];
  const settings = {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    permissions: { allow },
    hooks: HOOKS_BLOCK,
  };
  return JSON.stringify(settings, null, 2) + "\n";
}

function buildSettingsLocal(p: HarnessParams): string {
  const settings = {
    permissions: {
      allow: ["WebSearch", `Bash(${p.forgeCli} api:*)`],
      deny: [
        "Read(./**/dist/**)",
        "Read(./**/build/**)",
        "Read(./**/coverage/**)",
        "Read(./**/*.d.ts)",
        "Read(./**/*.map)",
        "Read(./**/*.gen.*)",
        `Read(./**/${p.lockfile})`,
        "Read(./**/node_modules/**)",
      ],
    },
  };
  return JSON.stringify(settings, null, 2) + "\n";
}

function buildClaudeMd(p: HarnessParams, root: string): string {
  const normative = readFileSync(join(root, "_normative.md"), "utf-8").replace(
    /^<!--[\s\S]*?-->\s*/,
    ""
  );
  const cmds = p.commands.length
    ? `- Commands: ${p.commands.map((c) => `\`${c}\``).join(", ")}.\n`
    : "";
  const body = `# Project guide

> Generated by agent-stack. Edit freely to describe your project.

## Tooling

- Package manager: **${p.packageManager}** only — other package managers are blocked by the guard-bash hook.
- Default branch: \`${p.mainBranch}\`. \`git push\` is manual-only.
- Never hand-edit generated files: ${p.generatedGlobs.split("|").join(", ")}, ${p.lockfile}.
${cmds}
## Subagent delegation

- **task-analyzer** at the start of a non-trivial task.
- **code-reviewer** after writing or modifying code.
- **test-writer** for unit tests.
- **pattern-scout** to (re)generate \`.claude/rules/\` after structural changes.

`;
  return body + normative;
}

function buildCodemap(): string {
  return `# CODEMAP

> Generated by agent-stack — replace with a real map of where things live (apps, packages, entry points).

| Path | What |
| --- | --- |
| \`src/\` | source |
| \`tests/\` | tests |

## Harness (not committed)

\`.claude/\`, \`CLAUDE.md\`, \`CODEMAP.md\` are git-excluded (\`.git/info/exclude\`) — personal harness, not project history.
`;
}

/** Build the full harness file set (pure — no IO side effects on the target). */
export function buildHarnessFiles(params: HarnessParams): GeneratedFile[] {
  const root = templatesRoot();
  const files: GeneratedFile[] = [];

  for (const abs of walk(root)) {
    if (basename(abs).startsWith("_")) continue; // generator input, not deployed
    const rel = relative(root, abs);
    const content = substitute(readFileSync(abs, "utf-8"), params);
    files.push({ path: join(".claude", rel), content, action: "create" });
  }

  files.push({ path: ".claude/settings.json", content: buildSettings(params), action: "create" });
  files.push({
    path: ".claude/settings.local.json",
    content: buildSettingsLocal(params),
    action: "create",
  });
  files.push({ path: "CLAUDE.md", content: buildClaudeMd(params, root), action: "create" });
  files.push({ path: "CODEMAP.md", content: buildCodemap(), action: "create" });

  return files;
}

/** Detect params, build the harness, write it to disk (chmod +x hooks). */
export async function emitHarness(projectDir: string): Promise<GeneratedFile[]> {
  const params = await detectHarnessParams(projectDir);
  const files = buildHarnessFiles(params);

  for (const f of files) {
    const full = join(projectDir, f.path);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, f.content, "utf-8");
    if (f.path.startsWith(".claude/hooks/") && f.path.endsWith(".sh")) {
      await chmod(full, 0o755);
    }
    log.success(f.path);
  }

  return files;
}
